on:
  release:
    # Sequence of patterns matched against refs/tags
    types:
      - created
      - published
      - edited

name: Publish Release

jobs:
  build:
    name: Publish Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: |
          echo "GITHUB_CONTEXT: $GITHUB_CONTEXT"

      # remove 'refs/tags' from string, for example from '/refs/tags/DCV-3.0.1' the outout will be 'DCV-3.0.1'
      - name: find and replace string in release
        id: tag
        uses: mad9000/actions-find-and-replace-string@2
        with:
          source: ${{ github.event.release.name }} # this translates to ref/heads/main on the main branch, but can be any arbitrary string 
          find: 'Release '        # we want to remove ref/heads/ from source 
          replace: ''               # and r
        run: |
          echo "GITHUB_CONTEXT: $GITHUB_CONTEXT"

      # check the output of the prev step
      - name: actions-ecosystem/action-regex-match@v2
        id: regex-match
        with:
          text: ${{ steps.tag.outputs.value }}
          regex: '^DCV-\d+[.]\d+[.]\d+$|^DCV-\d+[.]\d+[.]\d+[.]\d+$'
          flags: gm

#      - name: Publish release
#        if: ${{ steps.regex-match.outputs.match != '' }} ## if it is RC version. for exmaple: DCV-3.2.1-RC it won't publish 
#        uses: StuYarrow/publish-release@v1
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#        with:
#          id: ${{ steps.create_release.outputs.id }}

