on:
  release:
    # Sequence of patterns matched against refs/tags
    types:
      - created
      - published

name: Publish Release

jobs:
  build:
    name: Publish Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: |
          echo "GITHUB_CONTEXT: $GITHUB_CONTEXT"